services:
  eta-flow-space:
    image: nodered/node-red:4.1.3
    container_name: eta-flow-space
    ports:
      - "1895:1880"
    volumes:
      - ./flow-space:/data
    restart: unless-stopped
    environment:
      - TZ=Russia/Moscow
      - NODE_RED_ENABLE_PROJECTS=false
    entrypoint: >
      sh -c "
        cd /data && npm install
        exec node-red --userDir /data
      "
    networks:
      - eta-flow-space-network

  eta-flow-space-database:
    image: postgres:17
    container_name: eta-flow-space-database
    ports:
      - "35432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0987654321
      - POSTGRES_DB=eta_flow_space_database
    volumes:
      - ./flow-space-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - eta-flow-space-network

  eta-flow-space-ui:
    build:
      context: ./flow-space-ui/
      dockerfile: Dockerfile.ui
    container_name: eta-flow-space-ui
    ports:
      - "3000:80"
    restart: unless-stopped

    networks:
      - eta-flow-space-network

networks:
  eta-flow-space-network:
